version: "3"

services:
  api:
    build: .
    volumes:
      - .:/user/src/app
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
